[tool.poetry]
name = "nautilus_data"
version = "0.1.0"
description = ""
authors = ["Bradley McElroy <bradley.mcelroy@live.com>"]

[tool.poetry.dependencies]
python = ">=3.9,<3.11"
nautilus_trader = {git = "https://github.com/nautechsystems/nautilus_trader.git", branch = "develop"}

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
