[tool.poetry]
name = "nautilus_data"
version = "0.4.0"
description = ""
authors = ["Bradley McElroy <bradley.mcelroy@live.com>"]

[tool.poetry.dependencies]
python = ">=3.9, <3.11"
nautilus_trader = ">=1.163.0"
requests = "^2.28"

[build-system]
requires = ["poetry-core>=1.4.0"]
build-backend = "poetry.core.masonry.api"
